Repository kohyunsil/Algo_camping, pull requests merged in 2021-06, with the labels that each got.

#5 [feature/server] Naver map v5 category review selenium scraping
  camping_server/config.py
  camping_server/scraping/__init__.py
  camping_server/scraping/naverv5_category.py
  camping_server/scraping/naverv5_main.py
  camping_server/scraping/ogcamp_crawl.py
Labels: development, enhancement

#7 [feature/server] Uniformed sigungucode applied to API datas
  README.md
  camping_server/apis/__init__.py
  camping_server/apis/gocamping_api.py
  camping_server/apis/koreatour_api.py
  camping_server/apis/make_sigungucode.py
  camping_server/config.py
Labels: development, enhancement

#8 [feature/server] Naver map v5 selenium scraping Address NoSuchElement Error Fix
  camping_server/scraping/__init__.py
  camping_server/scraping/naverv5_category.py
Labels: enhancement

#11 [feature/client] feature/client Prototype v1.0
  camping_client/app/static/css/detail.css
  camping_client/app/static/css/header.css
  camping_client/app/static/css/index.css
  camping_client/app/static/css/searchlist.css
  camping_client/app/static/css/signin.css
  camping_client/app/static/css/signup.css
  camping_client/app/static/js/detail.js
  camping_client/app/static/js/swiper.js
  camping_client/app/static/js/swiper.min.js
  camping_client/app/static/js/thumbnail_swiper.js
  camping_client/app/templates/detail.html
  camping_client/app/templates/index.html
  camping_client/app/templates/layout/footer.html
  camping_client/app/templates/layout/header.html
  camping_client/app/templates/searchlist.html
  camping_client/app/templates/signin.html
  camping_client/app/templates/signup.html
  camping_client/app/views/routes.py
  camping_client/templates/index.html
Labels: development, good first issue

#12 [feature/client][feature/server1] TagsInput.js
  camping_server1/app.py
  camping_server1/app/__init__.py
  camping_server1/app/config.py
  camping_server1/app/model/__init__.py
  camping_server1/app/model/user_dao.py
  camping_server1/app/service/__init__.py
  camping_server1/app/service/user_service.py
  camping_server1/app/static/css/detail.css
  camping_server1/app/static/css/header.css
  camping_server1/app/static/css/index.css
  camping_server1/app/static/css/searchlist.css
  camping_server1/app/static/css/signin.css
  camping_server1/app/static/css/signup.css
  camping_server1/app/static/font/HARLOWSI_1.woff
  camping_server1/app/static/js/detail.js
  camping_server1/app/static/js/index.js
  camping_server1/app/static/js/swiper.js
  camping_server1/app/static/js/swiper.min.js
  camping_server1/app/static/js/tagsinput.js
  camping_server1/app/static/js/thumbnail_swiper.js
  camping_server1/app/templates/detail.html
  camping_server1/app/templates/index.html
  camping_server1/app/templates/layout/footer.html
  camping_server1/app/templates/layout/header.html
  camping_server1/app/templates/searchlist.html
  camping_server1/app/templates/signin.html
  camping_server1/app/templates/signup.html
  camping_server1/app/test/test_model.py
  camping_server1/app/test/test_service.py
  camping_server1/app/test/test_view.py
  camping_server1/app/view/__init__.py
  camping_server1/app/view/apis.py
  camping_server1/app/view/routes.py
  camping_server1/run.sh
Labels: bug, development
